# Generated by Django 3.1.7 on 2021-03-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0013_auto_20210224_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
